# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vlayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QTime
from PyQt5.QtWidgets import *
import sys
import xlrd
import sqlite3
from PyQt5.QtGui import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 252)

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 10, 351, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(20, 10, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 40, 581, 192))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "查找"))
        self.comboBox.setItemText(0, _translate("Form", "请选择查找的方式"))
        self.comboBox.setItemText(1, _translate("Form", "SN编号"))
        self.comboBox.setItemText(2, _translate("Form", "IP地址"))
        self.comboBox.setItemText(3, _translate("Form", "合同编号"))
        self.comboBox.setItemText(4, _translate("Form", "项目编号"))
        self.comboBox.setItemText(5, _translate("Form", "项目名称"))


class SearchGateway(QDialog):
    def __init__(self):
        QDialog.__init__(self)
        self.UI = Ui_Form()
        self.UI.setupUi(self)



        self.UI.pushButton.clicked.connect(lambda: self.Start_Search())

    def Start_Search(self,list):
        print("1")
        try:
            index = self.UI.comboBox.currentIndex()
            searchText = self.UI.lineEdit.text()
            if len(searchText) is 0:
                QMessageBox.information(self, '提示', '查找内容不能为空，请输入要搜索的内容！', QMessageBox.Yes)
                return

            if index == 1:
                list.setFilter(("SN = '%s'" % (searchText)))#通过SN查询
                list.select()
            # if index == 2:
            #     self.model.setFilter(("IP = '%s'" % (searchText)))
            #     self.model.select()
            # if index == 3:
            #     self.model.setFilter(("contract = '%s'" % (searchText)))#合同编号
            #     self.model.select()
            # if index == 4:
            #     self.model.setFilter(("item_number = '%s'" % (searchText)))#项目编号
            #     self.model.select()
            # if index == 5:
            #     self.model.setFilter(("project_name = '%s'" % (searchText)))#项目名称
            #     self.model.select()
            #

        except Exception as e:
            print(e)



if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = SearchGateway()
    mainWindow.show()
    sys.exit(app.exec_())