# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tatest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtGui,QtCore,QtWidgets,QtSql
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(850, 600)
        MainWindow.setFixedSize(1200, 650)  # 不能改变大小

        # MainWindow.setWindowFlags(
        #     QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowMaximizeButtonHint | QtCore.Qt.WindowCloseButtonHint)
        #MainWindow.setWindowTitle("返修网关维护表")
        MainWindow.setWindowIcon(QIcon('logo.png'))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # self.verticalLayout_3 = QtWidgets.QVBoxLayout(self)
        # self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 30, 1160, 741))
        self.tableView.setObjectName("tableView")

        # self.verticalLayout_3.addWidget(self.tableView)
        # self.verticalLayout_3.setStretch(0, 1)
        # self.verticalLayout_3.setStretch(1, 6)

        self.b_searchgateway = QtWidgets.QPushButton(self.centralwidget)
        self.b_searchgateway.setGeometry(QtCore.QRect(1100, 0, 80, 23))
        self.b_searchgateway.setObjectName("b_searchgateway")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(750, 0, 130, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("请选择查找的方式")
        self.comboBox.addItem("按SN查找")
        self.comboBox.addItem("按时间查找")
        self.comboBox.addItem("按IP查找")

        self.line_context = QtWidgets.QLineEdit(self.centralwidget)
        self.line_context.setGeometry(QtCore.QRect(890, 0, 200, 23))
        # self.line_context.setFixedSize(120, 30)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")

        fileMenu = self.menubar.addMenu('文件')
        editMenu = self.menubar.addMenu('编辑')
        viewMenu = self.menubar.addMenu('视图')
        # toolsMenu = self.menubar.addMenu('工具')
        # helpMenu = self.menubar.addMenu('帮助')

        # 创建一个action(行为)，标题为"exti"， self 为parent
        self.exitButton = QAction(QIcon("../image/退出系统.png"),'Exit', MainWindow)
        # 设置action的快捷键
        self.exitButton.setShortcut('Ctrl+Q')
        # 更改action的title
        self.exitButton.setText("退出")

        self.b_view_data = QAction(QIcon("../image/打开连接.png"),'View', MainWindow)
        self.b_view_data.setText("打开连接")

        self.b_close_data = QAction(QIcon("../image/关闭连接.png"), 'Close', MainWindow)
        self.b_close_data.setText("关闭连接")

        self.b_add_row = QAction(QIcon("../image/插入.png"),'Add', MainWindow)
        self.b_add_row.setText("添加")

        self.b_delete_row = QAction(QIcon("../image/删除.png"),'Del', MainWindow)
        self.b_delete_row.setText("删除")
        self.b_delete_row.setShortcut('Delete')

        self.b_import = QAction(QIcon("../image/导入.png"),'Import', MainWindow)
        self.b_import.setText("导入连接")

        self.b_export = QAction(QIcon("../image/导出.png"),'Export', MainWindow)
        self.b_export.setText("导出连接")

        self.b_refresh = QAction(QIcon("../image/刷新.png"), 'Refresh', MainWindow)
        self.b_refresh.setText("刷新")
        self.b_refresh.setShortcut('F5')

        self.b_save = QAction(QIcon("../image/保存.png"),'Save', MainWindow)
        self.b_save.setText("保存")
        self.b_save.setShortcut('Ctrl+S')

        self.b_recover = QAction(QIcon("../image/撤销.png"),'Recover', MainWindow)
        self.b_recover.setText("撤销")
        self.b_recover.setShortcut('Ctrl+Z')

        self.b_logs = QAction(QIcon("../image/日志.png"),'Log', MainWindow)
        self.b_logs.setText("历史日志")

        self.b_help = QAction(QIcon("../image/帮助.png"),'Help', MainWindow)
        self.b_help.setText("帮助文档")

        self.b_about = QAction('About', MainWindow)
        self.b_about.setText("关于")

        self.b_alls = QAction(QIcon("../image/显示.png"),'All', MainWindow)
        self.b_alls.setText("显示行标列标")

        self.b_part = QAction(QIcon("../image/隐藏.png"),'Part', MainWindow)
        self.b_part.setText("隐藏行标列标")


        # 可以将单个action按钮添加到菜单中：
        fileMenu.addAction(self.b_view_data)
        fileMenu.addAction(self.b_import)
        fileMenu.addAction(self.b_export)
        fileMenu.addAction(self.b_close_data)
        fileMenu.addAction(self.exitButton)

        editMenu.addAction(self.b_refresh)
        editMenu.addAction(self.b_add_row)
        editMenu.addAction(self.b_delete_row)
        editMenu.addAction(self.b_recover)
        editMenu.addAction(self.b_save)

        viewMenu.addAction(self.b_alls)
        viewMenu.addAction(self.b_part)

        # toolsMenu.addAction(self.b_logs)
        # helpMenu.addAction(self.b_help)
        # helpMenu.addAction(self.b_about)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "返修网关维护表"))
        self.b_searchgateway.setText(_translate("MainWindow", "查找"))

