# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore,QtWidgets
from PyQt5.QtWidgets import *
import sys
from PyQt5.QtGui import *
from import2 import Import2System



class Ui_Import3(object):
    def setupUi(self, Import3):
        Import3.setObjectName("Import3")
        Import3.setFixedSize(500, 300)
        Import3.setWindowIcon(QIcon('logo.png'))
        Import3.setStyleSheet("background-image:url(test.jpg)")

        self.radioButton = QtWidgets.QRadioButton(Import3)
        self.radioButton.setGeometry(QtCore.QRect(50, 80, 200, 21))
        self.radioButton.setObjectName("radioButton")

        self.radioButton_2 = QtWidgets.QRadioButton(Import3)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 50, 200, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setChecked(True)#默认选中

        self.radioButton_3 = QtWidgets.QRadioButton(Import3)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 110, 151, 21))
        self.radioButton_3.setObjectName("radioButton_3")

        self.radioButton_4 = QtWidgets.QRadioButton(Import3)
        self.radioButton_4.setGeometry(QtCore.QRect(50, 140, 121, 21))
        self.radioButton_4.setObjectName("radioButton_4")

        self.radioButton_5 = QtWidgets.QRadioButton(Import3)
        self.radioButton_5.setGeometry(QtCore.QRect(50, 170, 121, 21))
        self.radioButton_5.setObjectName("radioButton_5")

        self.pushButton = QtWidgets.QPushButton(Import3)
        self.pushButton.setGeometry(QtCore.QRect(300, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Import3)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 260, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label = QtWidgets.QLabel(Import3)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(Import3)
        QtCore.QMetaObject.connectSlotsByName(Import3)

    def retranslateUi(self, Import3):
        _translate = QtCore.QCoreApplication.translate
        Import3.setWindowTitle(_translate("Import3", "导入向导"))
        self.radioButton.setText(_translate("Import3", "CSV文件(*.csv)"))
        self.radioButton_2.setText(_translate("Import3", "Excel 97-2003 工作簿(*.xls)"))
        self.label.setText(_translate("Import3", "导入格式："))
        self.radioButton_3.setText(_translate("Import3", "Excel文件（*.xlsx）"))
        self.pushButton.setText(_translate("Import3", "下一步"))
        self.pushButton_2.setText(_translate("Import3", "取消"))
        self.radioButton_4.setText(_translate("Import3", "DBase文件(*.dbf)"))
        self.radioButton_5.setText(_translate("Import3", "文本文件(*.txt)"))


class Import3System(QDialog):
    def __init__(self):
        QDialog.__init__(self)
        self.UI = Ui_Import3()
        self.UI.setupUi(self)

        self.UI.pushButton.clicked.connect(lambda: self.Next_1())
        self.UI.pushButton_2.clicked.connect(lambda: self.cancel())

        self.UI.radioButton.setEnabled(False)  # 默认"开始导入"按钮不能点击
        self.UI.radioButton_3.setEnabled(False)  # 默认"开始导入"按钮不能点击
        self.UI.radioButton_4.setEnabled(False)  # 默认"开始导入"按钮不能点击
        self.UI.radioButton_5.setEnabled(False)  # 默认"开始导入"按钮不能点击


    def Next_1(self):
        print("1")
        import3 = Import2System()
        self.close()
        import3.exec_()

    def cancel(self):
        self.close()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = Import3System()
    mainWindow.show()
    sys.exit(app.exec_())